development:
  cloud_name: Rails.application.secrets.cloudinary_cloud_name
  api_key: Rails.application.secrets.cloudinary_api_key
  api_secret: Rails.application.secrets.cloudinary_api_secret

production:
  cloud_name: Rails.application.secrets.cloudinary_cloud_name
  api_key: Rails.application.secrets.cloudinary_api_key
  api_secret: Rails.application.secrets.cloudinary_api_secret