development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: lookbox
  pool: 5
  username: root
  password: ubuntu
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: lookbox_test
  pool: 5
  username: root
  password: ubuntu
  host: localhost

production:


#require "pry"
#class Dog
#  attr_accessor :name, :age
#  def initialize(*params)
#    binding.pry
#    @name = params.first
#    @age = params.last
#  end
#end
#
#d = Dog.new("Jim", 12)
#puts d.name + " - " + d.age
