development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: lookbox
  pool: <%= ENV["RAILS_MAX_THREADS"] || 5 %>
  username: root
  password: ubuntu
  #password: root
  host: localhost
  #host: db

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: lookbox_test
  pool: 5
  username: root
  password: ubuntu
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: lookbox
  pool: <%= ENV["RAILS_MAX_THREADS"] || 5 %>


