# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf8a324d092d4d9d6b2e480a353522d05423c30d71707f7f42660a8550d1c9e7d8d73eb749e735e809565c93e9e29952ebb909092fc5428b9788c1998068b9ad
#  google_app_id: "546568985147-ogf8nf5gmm06g717ek31lnr1mbpc1v5t.apps.googleusercontent.com"
#  google_app_secret: "KxS4pgE9rj49HRbUBoZRzIbN"
  google_app_id: <%= ENV["GOOGLE_APP_ID"] %>
  google_app_secret: <%= ENV["GOOGLE_APP_SECRET"] %>
  gmail_user_name: <%= ENV["GMAIL_USER_NAME"] %>
  gmail_user_password: <%= ENV["GMAIL_USER_PASSWORD"] %>
  cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
  cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
  use_cloudinary: <%= ENV["USE_CLOUDINARY"]%>
  cloudinary_folder: <%= ENV["CLOUDUNARY_ENV_FOLDER"]%>

test:
  secret_key_base: 0ed4dece30e1f0f551406f534c9c0ae90fca9f840c3de326ecaeefa0e191cd279e326af047e795ce3ac95cb754e883891f3e68e0c92077e2895ddf264e6f728f
  google_app_id: <%= ENV["GOOGLE_APP_ID"] %>
  google_app_secret: <%= ENV["GOOGLE_APP_SECRET"] %>
  gmail_user_name: <%= ENV["GMAIL_USER_NAME"] %>
  gmail_user_password: <%= ENV["GMAIL_USER_PASSWORD"] %>
  use_cloudinary: <%= ENV["USE_CLOUDINARY"]%>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_app_id: <%= ENV["GOOGLE_APP_ID"] %>
  google_app_secret: <%= ENV["GOOGLE_APP_SECRET"] %>
  gmail_user_name: <%= ENV["GMAIL_USER_NAME"] %>
  gmail_user_password: <%= ENV["GMAIL_USER_PASSWORD"] %>
  use_cloudinary: <%= ENV["USE_CLOUDINARY"]%>
  cloudinary_folder: <%= ENV["CLOUDUNARY_ENV_FOLDER"]%>
