---
development:
  :concurrency: 1
production:
  :concurrency: 5
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:queues:
  - default
  - mailers
  - lookbox_default
  - lookbox_mailers
#:daemon: true